[mainnet."Ethereum"]
rpc = "https://rpc.ankr.com/eth"
explorer_url = "https://etherscan.io"
symbol = "ETH"

[mainnet."BNB Chain"]
rpc = "https://rpc.ankr.com/bsc"
explorer_url = "https://bscscan.com"
symbol = "BNB"

[mainnet."Polygon"]
rpc = "https://polygon.llamarpc.com"
explorer_url = "https://polygonscan.com"
symbol = "MATIC"

[testnet."Ethereum Goerli Testnet"]
rpc = "https://eth-goerli.public.blastapi.io"
explorer_url = "https://goerli.etherscan.io"
symbol = "gETH"

[testnet."BNB Chain Testnet"]
rpc = "https://bsc-testnet.publicnode.com"
explorer_url = "https://testnet.bscscan.com"
symbol = "tBNB"

[testnet."Avalanche Testnet"]
rpc = "https://endpoints.omniatech.io/v1/avax/fuji/public"
explorer_url = "https://testnet.snowtrace.io"
symbol = "tAVAX"

[testnet."Polygon Testnet"]
rpc = "https://matic-mumbai.chainstacklabs.com"
explorer_url = "https://mumbai.polygonscan.com"
symbol = "tMATIC"

[testnet."Fantom Testnet"]
rpc = "https://fantom-testnet.publicnode.com"
explorer_url = "https://testnet.ftmscan.com"
symbol = "tFTM"