LOGGING_LEVEL = "INFO"
DELAY = [5, 20]
TOKEN_STANDARDS = ["ERC721"]

[BRIDGE_CHAINS]
MAINNET = ["Ethereum", "BNB Chain", "Polygon"]
TESTNET = ["Ethereum Goerli Testnet", "BNB Chain Testnet", "Polygon Testnet"]

[MESSENGER_CHAINS]
MAINNET = ["BNB Chain", "Polygon"]
TESTNET = []
