[mainnet."Ethereum"]
zkbridge_id = "628ee590c2c552fd1a61a7a8"
chain_id = 1
currency = "ETH"
decimals = 18
explorer = "https://api.etherscan.io/api"
RPC = "https://rpc.ankr.com/eth"

#[mainnet.arbitrum]
#chain_id = 42161
#currency = "ETH"
#explorer = "https://api.arbiscan.io/api"
#RPC = "https://rpc.ankr.com/arbitrum"

[mainnet."BNB Chain"]
zkbridge_id = "628eeca4c2c552fd1a61a7a9"
chain_id = 56
currency = "BNB"
decimals = 18
explorer = "https://api.bscscan.com/api"
RPC = "https://rpc.ankr.com/bsc"

[testnet."BNB Chain Testnet"]
zkbridge_id = "632971cd3f606cf1601f7eab"
chain_id = 97
currency = "BNB"
decimals = 18
explorer = "https://api.testnet.bscscan.com/api"
RPC = "https://bsc-testnet.publicnode.com"

[testnet."Ethereum Goerli Testnet"]
zkbridge_id = "627f65274c42972511443130"
chain_id = 5
currency = "ETH"
decimals = 18
explorer = "https://api.goerli.etherscan.io/api"
RPC = "https://eth-goerli.public.blastapi.io"

[testnet."Avalanche Testnet"]
zkbridge_id = "6341486d3c278eefaee896e2"
chain_id = 43113
currency = "AVAX"
decimals = 18
explorer = "https://api.testnet.snowtrace.io/api"
RPC = "https://endpoints.omniatech.io/v1/avax/fuji/public"

[testnet."Polygon Testnet"]
zkbridge_id = "6329724a3f606cf1601f7eac"
chain_id = 80001
currency = "MATIC"
decimals = 18
explorer = "https://api.mumbai.polygonscan.com/api"
RPC = ""

[testnet."Fantom Testnet"]
zkbridge_id = "6226df2898944273d0703789"
chain_id = 4002
currency = "FTM"
decimals = 18
explorer = "https://api.testnet.ftmscan.com/api"
RPC = ""
